// <auto-generated />
namespace core_manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Languages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Languages));
        
        string IMigrationMetadata.Id
        {
            get { return "201803222302144_Languages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
